name: Build and Deploy
concurrency: production

on:
  push:
    branches:
      - main
jobs:
  deploy-service:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/build-service.yml

  deploy-frontend:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/build-frontend.yml
