name: Root build 

on:
  push:
    branches:
      - $default-branch
jobs:
  dummy:
    steps:
      - run: echo "I'm just  a dummy step"
  deploy-service:
    uses: ./.github/workflows/build-service.yml
  deploy-frontend:
    uses: ./.github/workflows/test-frontend.yml
