name: Build and Deploy
concurrency: production

on:
  push:
    branches:
      - main
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm just a dummy step"

  deploy-service:
    uses: ./.github/workflows/build-service.yml

  deploy-frontend:
    uses: ./.github/workflows/test-frontend.yml
