name: Run tests

on:
  push

jobs:
  test-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/patient_service
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: cd apps/patient_service
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/patient_frontend
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: cd apps/patient_frontend
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
