name: Root tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test-service:
    uses: UriCW/innohealth-challenge/.github/workflows/test-service.yml@deployment
  #  test-frontend:
  #    uses: ./.github/workflows/test-frontend.yml
