name: Test Frontend

on:
  workflow_call:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/patient_frontend
    strategy:
      matrix:
        node-version: [21.x]
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      run: |
          npm ci
          npm run build --if-present

    - name: Test
      run: npm test
